[package]
name = "graphics"
version = "0.1.0"
authors = ["ruoshui <rmao10@stuy.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"
thiserror = "1.0"
indicatif = "0.15.0"